### ISSUE TITLE
Internal Server Error during configuration

### ISSUE THREAD

**Issue by enzoantonino** [akenza-io/grafana-connector#14]
I'm having this issue, can you please help? 

<img width="1364" alt="Schermata 2021-10-02 alle 00 29 26" src="https://user-images.githubusercontent.com/23216464/135692628-7bb8bb17-ffeb-4dbd-bb78-5461d5ce1cdb.png">

The http call that gives this error is 
<img width="388" alt="Schermata 2021-10-02 alle 00 30 52" src="https://user-images.githubusercontent.com/23216464/135692724-03560e47-c443-41e3-8a59-975b63252c48.png">

Thanks in advance, 
Enzo

**Comment by mariusgiger** [comment]
Hi @enzoantonino, as you are using the new version of our platform, you will need to use the [Akenza Grafana Connector](https://github.com/akenza-io/grafana-connector-v3#akenza-grafana-connector) instead. More information can be found [here](https://docs.akenza.io/api-reference/advanced-topics/grafana-data-source-plugin).

Let me know if you have any further questions or issues.

Cheers,
Marius

**Comment by enzoantonino** [comment]
Hi @mariusgiger, thank you! [Akenza Grafana Connector](https://github.com/akenza-io/grafana-connector-v3#akenza-grafana-connector) resolved the issue! 

Cheers, 
Enzo
